name: Android CI

on:
  push:
    branches:
      - GOGO
  pull_request:
    branches:
      - GOGO

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Find APK and Mapping files
        id: find_outputs
        run: |
          APK=$(find app/build/outputs/apk -type f -name "*release*.apk" | head -n 1)
          MAPPING=$(find app/build/outputs/mapping -type f -name "*release*.txt" | head -n 1)
          echo "APK_PATH=$APK" >> $GITHUB_ENV
          echo "MAPPING_PATH=$MAPPING" >> $GITHUB_ENV
          echo "Found APK: $APK"
          echo "Found Mapping: $MAPPING"

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shushify-ci-release
          path: |
            ${{ env.APK_PATH }}
            ${{ env.MAPPING_PATH }}

      - name: Create AutoBuild Release
        run: |
          GIT_DESCRIBE=$(git rev-parse --short HEAD)
          VERSION=$(grep 'versionName = ' app/build.gradle | sed 's/.*versionName = "\(.*\)".*/\1/')
          mv "${{ env.APK_PATH }}" Shushify-v${VERSION}.apk
          gh release delete autobuild --yes || true
          gh release create autobuild Shushify-v${VERSION}.apk --latest --title "Shushify v${VERSION} (${GIT_DESCRIBE})" --notes "This is an auto build by Github Android CI"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
